# Change these first
owner: GavinDR1 # Your GitHub organization or username, where this repository lives
repo: Monitor # The name of this repository

sites:
  - name: Drip Server
    url: $DRIP_SERVER
  - name: ModMail
    url: https://modmailbot.gavindr1.repl.co
  - name: Countr
    url: https://darkamusingcomputeranimation.gavindr1.repl.co
    expectedStatusCodes:
      - 426
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: dark
 # cname: demo.upptime.js.org
  baseUrl: /Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Gavin Bots Status Manager
  introTitle: "**Status Manager**"
  introMessage: This is a waste of time of your life of reading this, go do something else like read a book or play a game or go outside or idk just do something else.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
